openapi: 3.0.1
paths:
  /hellosummer/hello/{name}:
    get:
      operationId: hello
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                type: string
  /hellosummer/hello/post:
    post:
      operationId: helloPost
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/JsonNode'
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                type: string
  /helloplugin/hello/{name}:
    get:
      operationId: hello_1
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                type: string
  /helloplugin/hello/post:
    post:
      operationId: helloPost_1
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/JsonNode'
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    JsonNode:
      type: object
