openapi: 3.0.1
paths:
  /hellosummer1/hello/{name}:
    get:
      operationId: hello
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: "key !@#$%^&*()_+-=[]\\{}|;':\",./<>? 中文 "
        in: query
        schema:
          type: string
      - name: color
        in: path
        required: true
        style: matrix
        schema:
          type: string
      - name: color2
        in: path
        required: true
        style: matrix
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/MyResponse'
  /hellosummer1/hello/post:
    post:
      operationId: helloPost
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/JsonNode'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/MyResponse'
  /helloplugin/hello/{name}:
    get:
      operationId: hello_1
      parameters:
      - name: name
        in: path
        required: true
        schema:
          pattern: "[a-zA-Z\\@\\.' ]{1,10}"
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/MyResponse'
  /helloplugin/hello/post:
    post:
      operationId: helloPost_1
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/JsonNode'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/MyResponse'
components:
  schemas:
    MyResponse:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
        ts:
          type: string
          format: date-time
    JsonNode:
      type: object
