############################################################
# 1. gRpc.server Network Listeners                         #
# Format: ip1:port1, ip2:port2, ..., ipN:portN             #
# Example: 192.168.1.10:8424, 127.0.0.1:8424, 0.0.0.0:8424 #
############################################################
gRpc.server.bindings=0.0.0.0:8881
#gRpc.server.autostart=true
## valid value = CPU (default), IO, Mixed
#gRpc.server.pool.BizExecutor.mode=CPU

#gRpc.server.pool.coreSize=
#gRpc.server.pool.maxSize=
#gRpc.server.pool.queueSize=2147483647
#gRpc.server.pool.keepAliveSeconds=60


###########################
# 2. gRpc.server keystore #
###########################
gRpc.server.ssl.KeyStore=keystore.p12
gRpc.server.ssl.KeyStorePwd=ENC(xf3jrVGMrv2SzBGtDte2bQ==)
gRpc.server.ssl.KeyAlias=demo1.com
gRpc.server.ssl.KeyPwd=ENC(lkLQErGnHwmwgCcNyIewcg==)


#############################
# 3. gRpc.server truststore #
#############################
#gRpc.server.ssl.TrustStore=
#gRpc.server.ssl.TrustStorePwd=DEC()
