############################################################
# 1. gRpc.client provider                                  #
# Format: ip1:port1, ip2:port2, ..., ipN:portN             #
# Example: 192.168.1.10:8424, 127.0.0.1:8425, 0.0.0.0:8426 #
############################################################
#gRpc.client.LoadBalancing.servers=192.168.1.11:8882, 127.0.0.1:8881
## tcp://127.0.0.1:8424
## tls://127.0.0.1:8424
## unix:/tmp/grpcsrver.socket
gRpc.client.target.url=tcp://127.0.0.1:8424

#gRpc.client.ssl.Protocols=TLSv1.3
#gRpc.client.ssl.ciphers=


###########################
# 2. gRpc.client keystore #
###########################
#gRpc.client.ssl.KeyStore=
#gRpc.client.ssl.KeyStorePwd=DEC()
#gRpc.client.ssl.KeyAlias=
#gRpc.client.ssl.KeyPwd=DEC()


#############################
# 3. gRpc.client truststore #
#############################
#gRpc.client.ssl.TrustStore=
#gRpc.client.ssl.TrustStorePwd=DEC()
#gRpc.client.ssl.overrideAuthority=
