#########################
# My Header description #
#########################
#plugin.licenseKey=DEC(plain text here will be automatically encrypted by app root password, specified by -authfile or -auth, when the application starts or is running)
